<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>AccuratPanelCWD</RootNamespace>
		<AssemblyName>ACCURAT - Панель управления</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="packages\**" />
	  <EmbeddedResource Remove="packages\**" />
	  <None Remove="packages\**" />
	  <Page Remove="packages\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
		<PackageReference Include="NLog" Version="6.1.2" />
		<PackageReference Include="Polly" Version="8.6.6" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AccuratSystem.Contracts\AccuratSystem.Contracts.csproj" />
	</ItemGroup>
</Project>