// <auto-generated />
using System;
using System.Collections.Generic;
using Accurat.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accurat.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527192002_AddAdminIdToOrder")]
    partial class AddAdminIdToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accurat.WebAPI.Models.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.DTOs.UpsellSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("SuggestedServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TriggerServiceId");

                    b.ToTable("UpsellSuggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusAmount = 150m,
                            Message = "Клиент выбрал стандартную мойку. Предложите покрыть кузов кварцем для защиты от грязи и блеска!",
                            SuggestedServiceId = 6,
                            TriggerServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            BonusAmount = 50m,
                            Message = "В комплекс не входит антидождь/глубокая чистка стекол. Отличный шанс предложить эту услугу!",
                            SuggestedServiceId = 3,
                            TriggerServiceId = 2
                        });
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ServiceLiftsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WashBaysCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Строителей, 54",
                            Name = "ACCURAT - На Строителей",
                            ServiceLiftsCount = 0,
                            Type = 1,
                            WashBaysCount = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Луначарского, 26а",
                            Name = "ACCURAT - На Луначарского",
                            ServiceLiftsCount = 3,
                            Type = 3,
                            WashBaysCount = 3
                        });
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarModel")
                        .HasColumnType("text");

                    b.Property<string>("CarNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultDiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<int>("VisitsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModel = "ВАЗ 2105",
                            CarNumber = "В583КВ43",
                            DefaultDiscountPercent = 0m,
                            FullName = "Кураедов Дмитрий Витальевич",
                            Notes = "Разработчик",
                            Phone = "+79996094363",
                            RegistrationDate = new DateTime(2001, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalSpent = 0m,
                            VisitsCount = 0
                        });
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.EmployeeScheduleEntry", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId", "Year", "Month", "Day");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("BodyTypeCategory")
                        .HasColumnType("integer");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("CarBodyType")
                        .HasColumnType("text");

                    b.Property<string>("CarModel")
                        .HasColumnType("text");

                    b.Property<string>("CarNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtraCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ExtraCostReason")
                        .HasColumnType("text");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsAppointment")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalTotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("ServiceIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Time");

                    b.HasIndex("BranchId", "Department", "Time");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ClientPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId", "Category");

                    b.ToTable("OrderExpenses");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PriceNote")
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("OrderId", "ServiceId");

                    b.ToTable("OrderServiceItems");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "EndTime");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderTimelineEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId", "Timestamp");

                    b.ToTable("OrderTimelineEntries");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderWasher", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SplitShare")
                        .HasColumnType("numeric");

                    b.Property<int?>("WasherId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("WasherId");

                    b.ToTable("OrderWashers");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePriceHint")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CustomWagePercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("HasFloatingPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PriceByBodyType")
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2-х фазная мойка",
                            DurationMinutes = 40,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "Стандартная мойка кузова",
                            PriceByBodyType = "{\"1\":1150,\"2\":1250,\"3\":1500,\"4\":1750}",
                            ServiceCategory = "Wash"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Двухфазная мойка, пылесос, уборка",
                            DurationMinutes = 90,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "КОМПЛЕКС ACCURAT",
                            PriceByBodyType = "{\"1\":2150,\"2\":2350,\"3\":2700,\"4\":3150}",
                            ServiceCategory = "Wash"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Внутренняя и внешняя очистка",
                            DurationMinutes = 15,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "Чистка стекол",
                            PriceByBodyType = "{\"1\":350,\"2\":350,\"3\":350,\"4\":350}",
                            ServiceCategory = "Wash"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Уборка салона",
                            DurationMinutes = 20,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "Пылесос салона",
                            PriceByBodyType = "{\"1\":350,\"2\":350,\"3\":350,\"4\":350}",
                            ServiceCategory = "Wash"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Уборка пластика",
                            DurationMinutes = 15,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "Влажная уборка",
                            PriceByBodyType = "{\"1\":350,\"2\":350,\"3\":350,\"4\":350}",
                            ServiceCategory = "Wash"
                        },
                        new
                        {
                            Id = 6,
                            Description = "SHINE SYSTEM",
                            DurationMinutes = 20,
                            HasFloatingPrice = false,
                            IsActive = true,
                            Name = "Кварцевое покрытие",
                            PriceByBodyType = "{\"1\":1000,\"2\":1000,\"3\":1000,\"4\":1000}",
                            ServiceCategory = "Wash"
                        });
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<int>>("EmployeeIds")
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalaryPerShift")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseWagePercentage")
                        .HasColumnType("numeric");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalaryPerShift = 0m,
                            BaseWagePercentage = 0m,
                            FullName = "Анастасия",
                            IsActive = true,
                            Login = "а1",
                            PasswordHash = "1",
                            Phone = "+79877063709",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Accurat.WebAPI.Models.TenantFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCrmMarketingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStorageEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTelegramBossEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUpsellEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.ToTable("TenantFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            IsCrmMarketingEnabled = false,
                            IsStorageEnabled = false,
                            IsTelegramBossEnabled = false,
                            IsUpsellEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            IsCrmMarketingEnabled = false,
                            IsStorageEnabled = false,
                            IsTelegramBossEnabled = false,
                            IsUpsellEnabled = true
                        });
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Order", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderExpense", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderServiceItem", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccuratSystem.Contracts.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderTimelineEntry", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.OrderWasher", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Order", "Order")
                        .WithMany("OrderWashers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccuratSystem.Contracts.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccuratSystem.Contracts.Models.User", "Washer")
                        .WithMany()
                        .HasForeignKey("WasherId");

                    b.Navigation("Order");

                    b.Navigation("Washer");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Shift", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Transaction", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccuratSystem.Contracts.Models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("AccuratSystem.Contracts.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.User", b =>
                {
                    b.HasOne("AccuratSystem.Contracts.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AccuratSystem.Contracts.Models.Order", b =>
                {
                    b.Navigation("OrderWashers");
                });
#pragma warning restore 612, 618
        }
    }
}
